$words = @(
"the","and","that","have","for","not","with","you","this","but","from","they","what",
"been","were","when","their","which","like","time","very","after","then","some","into",
"could","state","only","other","way","where","each","those","may","such","about","many",
"two","being","well","also","more","first","these","second","made","most","over","said",
"each","which","may","down","water","found","yet","still","place","while","thought",
"world","small","using","line","come","mights","call","called","four","wanted","show",
"every","start","hand","old","life","tell","become","high","own","end","kept","begin",
"head","house","large","program","same","best","why","turn","right","study","should",
"eyes","going","never","before","word","work","last","long","need","felt","brain",
"neural","network","learning","memory","system","think","human","cognition","thought",
"science","nature","life","mind","body","energy","quantum","physics","biology",
"chemistry","evolution","cell","gene","protein","sequence","molecule","reaction",
"structure","process","algorithm","data","model","training","inference","prediction",
"classification","generation","language","text","token","embedding","dimension",
"manifold","space","geometry","topology","neuron","synapse","connectome","sensory",
"motor","interneuron","command","action","sparse","dense","stream","echo","reservoir",
"hebbian","association","goldworm","computer","code","software","hardware","circuit",
"processor","communication","concept","idea","meaning","understanding","reasoning",
"logic","mathematics","coordinate","vector","matrix","tensor","transformation",
"entropy","signal","noise","threshold","gate","activation","creative","deterministic",
"softmax","entmax","sparsemax","alpha","temperature","weight","bias","gradient",
"descent","optimization","attention","layer","deep","artificial","intelligence",
"machinelearning","corpus","document","sentence","paragraph","chapter","book",
"article","paper","research","experiment","observation","analysis","result",
"conclusion","hypothesis","theory","animal","plant","bacteria","virus","tissue",
"organism","philosophy","psychology","neuroscience","genetics","ecology","environment",
"climate","weather","geography","astronomy","engineering","technology","social",
"culture","society","economy","politics","history","art","music","literature","story",
"narrative","poem","film","design","imagination","dream","feeling","emotion","sense",
"perception","awareness","health","disease","medicine","treatment","therapy","cure",
"prevention","cause","food","earth","fire","wind","sky","ocean","mountain","valley",
"river","forest","desert","island","coast","hill","plain","field","garden","city",
"town","village","home","house","building","room","door","window","floor","wall",
"paper","letter","symbol","number","digit","color","sound","smell","taste","touch",
"texture","shape","size","width","bright","dark","light","shadow","firm","gentle",
"rough","smooth","dull","happy","sad","angry","afraid","surprised","excited","calm",
"confused","bored","tired","possible","impossible","simple","complex","difficult",
"vague","certain","uncertain","specific","general","particular","universal","whole",
"component","person","child","adult","woman","girl","mother","father","brother",
"sister","daughter","friend","enemy","ally","partner","colleague","doctor","nurse",
"teacher","engineer","scientist","artist","writer","musician","poet","farmer","cook",
"gardener","builder","electrician","painter","dog","cat","bird","fish","horse",
"cow","sheep","pig","chicken","rabbit","turtle","tree","flower","grass","leaf",
"root","branch","bark","fruit","seed","soil","rain","sun","moon","star","planet",
"galaxy","universe","cosmos","infinite","eternal","behavior","movement","change",
"creation","storage","retrieval","recall","recognition","pattern","organization",
"property","quality","attribute","feature","aspect","connection","correlation",
"dependency","effect","outcome","consequence","influence","impact","problem","solution",
"answer","question","puzzle","goal","purpose","objective","intention","strategy",
"method","technique","procedure","decision","choice","option","alternative",
"potential","danger","threat","weakness","advantage","benefit","profit","reward",
"success","failure","achievement","milestone","progress","development","improvement",
"adaptation","stability","balance","harmony","coherence","consistency","diversity",
"variety","similarity","analogy","comparison","contrast","instance","demonstration",
"explanation","interpretation","evidence","proof","verification","validation",
"conjecture","assumption","premise","principle","regulation","standard","criterion",
"value","ethic","moral","virtue","justice","fairness","equality","obligation",
"responsibility","accountability","authority","freedom","liberty","autonomy",
"knowledge","information","fact","wisdom","insight","comprehension","consciousness",
"experience","practice","exercise","repetition","skill","ability","capability",
"competence","proficiency","expertise","mastery","excellence","imagination",
"invention","innovation","discovery","exploration","examination","neural","thinking",
"intelligent","reason","algorithmic","compute","computational","computing",
"inferring","orthogonal","basis","orthonormal","trajectory","resonance","plasticity",
"plastic","cognitive","cognit","resonant","substrate","module","engine","routing",
"route","geodesic","metric","dimensional","dimension","radius","sphere","circle",
"plane","fluid","wave","chain","branch","edge","core","shell","channel","zone",
"band","gram","meter","scope","stat","phase","gen","plasm","cyte","nucleus","cell",
"tissue","organ","head","foot","eye","ear","nose","mouth","heart","lung","liver",
"kidney","skin","bone","muscle","nerve","blood","dna","rna","atom","crystal",
"lattice","bond","enzyme","catalyst","acid","metal","glass","plastic","fiber",
"film","sheet","plate","rod","wire","tube","pipe","valve","pump","motor","engine",
"gear","shaft","bearing","spring","filter","switch","relay","amplifier","oscillator",
"modulator","encoder","decoder","transmitter","receiver","antenna","cable","browser",
"server","client","file","image","video","audio","speech","voice","sound","beat",
"rhythm","melody","harmony","chord","scale","tone","pitch","tempo","speed","rate",
"flow","stream","queue","stack","heap","map","list","array","bag","multiset",
"wormbrain","wormconnect","wormneural","wormcognitive","wormengine","wormcortex",
"wormplastic","wormentropy","wormmanifold","wormgeometry","wormtopology","wormmetric",
"wormsignal","wormstate","wormaction","wormmemory","wormreservoir","wormhippocampus",
"wormdendrite","wormaxon","wormcognit","wormsubstrate","wormmodule","wormprocess",
"wormroute","wormtrajectory","wormresonant","wormassociat","wormsynapse"
)

$seen = @{}
$unique = [System.Collections.Generic.List[string]]::new()
foreach ($w in $words) {
    $w = $w.Trim().ToLower()
    if ($w.Length -ge 3 -and -not $seen.ContainsKey($w)) {
        $seen[$w] = 1
        $unique.Add($w)
    }
}
$unique = $unique | Sort-Object -Unique
$unique | Out-File -FilePath 'C:\Users\Student\GoldWorm\static_vocabulary.txt' -Encoding UTF8
Write-Output "Generated $($unique.Count) vocabulary words"
